name: Build Mod (NeoForge)

on:
  push:
    branches: [ main, master, "26.2", "1.21.1" ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build NeoForge only
        run: ./gradlew remapNeoforgeJar --no-daemon --stacktrace

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: rprenames-neoforge-1.21.1
          path: build/libs/*.jar